steps:
  - label: DeepSeek + pplx
    gpu: h200
    source_file_dependencies:
      - vllm/
    command: VLLM_ALL2ALL_BACKEND=pplx VLLM_USE_DEEP_GEMM=1 vllm bench throughput --model deepseek-ai/DeepSeek-R1 --tensor-parallel-size 8 --input-len 1000 --output-len 1000 --num-prompts 50

  - label: DeepSeek + pplx v2
    gpu: h200
    num_gpus: 8
    source_file_dependencies:
      - vllm/
    command: VLLM_ALL2ALL_BACKEND=pplx VLLM_USE_DEEP_GEMM=1 vllm bench throughput --model deepseek-ai/DeepSeek-R1 --tensor-parallel-size 8 --input-len 1000 --output-len 1000 --num-prompts 50

  - label: DeepSeek + nixl
    gpu: h200
    source_file_dependencies:
      - vllm/
    num_gpus: 8
    command: VLLM_ALL2ALL_BACKEND=nixl VLLM_USE_DEEP_GEMM=1 vllm bench throughput --model deepseek-ai/DeepSeek-R1 --tensor-parallel-size 8 --input-len 1000 --output-len 1000 --num-prompts 50


  - label: "Qwen EP: pplx + DeepGEMM"
    gpu: h200
    num_gpus: 8
    commands:
      - VLLM_ALL2ALL_BACKEND=pplx VLLM_USE_DEEP_GEMM=1 vllm bench throughput --model Qwen/Qwen2-57B-A14B --tensor-parallel-size 1 --data-parallel-size 8 --enable-expert-parallel --input-len 1000 --output-len 1000 --num-prompts 50

  - label: "Qwen EP: DeepEP + DeepGEMM"
    gpu: h200
    num_gpus: 8
    commands:
      - VLLM_ALL2ALL_BACKEND=deepep VLLM_USE_DEEP_GEMM=1 vllm bench throughput --model Qwen/Qwen2-57B-A14B --tensor-parallel-size 1 --data-parallel-size 8 --enable-expert-parallel --input-len 1000 --output-len 1000 --num-prompts 50

  - label: "Qwen EP: DeepEP only"
    gpu: h200
    num_gpus: 8
    commands:
      - VLLM_ALL2ALL_BACKEND=deepep vllm bench throughput --model Qwen/Qwen2-57B-A14B --tensor-parallel-size 1 --data-parallel-size 8 --enable-expert-parallel --input-len 1000 --output-len 1000 --num-prompts 50
